; ---------------------------------------------------------------------------
; fpga.inc
; handy info about locations in the FPGA
; 03-04-19 E. Brombaugh
; ---------------------------------------------------------------------------

.define   GPIO_DATA $F200    ;  GPIO data register location
.define   ACIA_CTRL $F000    ;  ACIA control register location
.define   ACIA_DATA $F001    ;  ACIA data register location

